### ISSUE TITLE
Automate NPM publishing on GitHub Release

### ISSUE THREAD

**Issue by moodmosaic** [stacks-network/rendezvous#89]
Cutting a release off of a tag should trigger a GitHub Action to publish package on NPM registry. Need:

1. Add NPM_TOKEN to repo secrets
2. Example workflow:

```yaml
name: npm-publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```

Using Node.js 22 LTS for longest support timeline (until October 2026 as per the [release schedule](https://nodejs.org/en/about/previous-releases)).
